def variable_arguments(*n):
    print("list:",n)
variable_arguments(11)
variable_arguments("aaaa")
variable_arguments(11,22)
variable_arguments('AAAAA','BBBBB')
variable_arguments(11,22,33)
variable_arguments('aaaa','bbbbbb','ccccccc')
variable_arguments(11,22,33,44)
variable_arguments('AAAA','BBBBB','CCCCC','DDDDD')
variable_arguments(1111,22222,'QQQQQ','RRRRRR','WWWWW')
